### ISSUE TITLE
Logbook 4

### ISSUE THREAD

**Issue by SmritiGrg** [SmritiGrg/FYP-FoodiesArchive#5]
# Logbook: 3
**Meeting No:** 3                                 
**Date:** 2024-12-04
**Start Time:** 11 A.M
**End Time:** 11:50 A.M

## Items Discussed
1.	Application Programming Interface (API)
      -  Short discussion on APIs and recommended reading the book “APIs You Won’t Hate”.
2.	Hyper Text Transfer Protocol (HTTP)
      -  Briefly discussion on HTTP methods for CRUD operations, format of request, and format of response.
      -  To read the documentation on HTTP by the Mozilla Developer Network(MDN) website.
3.	HTTP Stateless
       - Short discussion about HTTP being stateless and a solution to overcome stateless by using session and cookies(sessid).
4.	Socket Communication
       - A short discussion on the socket a two-way communication channel.
 
## Achievements
- [ ] Created a level 0 and level 1 Data Flow Diagram (DFD) for the project to show the flow of data in the system.
- [ ] Created level 0 and level 1 Data flow diagram for the Get Subscription process.
- [ ] Created a Use Case Diagram.
- [ ] High Level and Expanded Use Case Description of Get Subscription Use case.
- [ ] Created a Collaboration Diagram of the Get Subscription Use case.
- [ ] Created a Sequence Diagram of the Get Subscription Use case.

## Tasks for the Next Meeting:
- User Registration and Login features.
- Other authentication features – Forgot password.

**Comment by SmritiGrg** [comment]
[Logsheet_4.docx](https://github.com/user-attachments/files/18467405/Logsheet_4.docx)

**Comment by SmritiGrg** [comment]
![Image](https://github.com/user-attachments/assets/b126be07-3c8e-47b9-8521-ec43463c2f60)
